server:
  port: 8090 # Config server? ??? ??

spring:
  application:
    name: pet-service  # ?? ??? Git ???? ??? .yml ??? ??? ??

    #??? ???? ?? ?? ??

  config:
    import: "optional:configserver:"
    cloud:
      config:
        uri: http://localhost:8888 #config server? url